startPoints = {
    ["visual"] = 9,
    ["performance"] = 7,
}

categories = {
    ["visual"] = {
        {
            name = "Wloty na dachu",
            type = "roof",
            icon = "files/images/roof.png",
            offset = Vector3(2, 2, 0),
            component = "ug_roof",
        },
        {
            name = "Wloty na masce",
            type = "hood",
            icon = "files/images/hood.png",
            offset = Vector3(2, 2, 0),
            component = "bonnet_dummy",
        },
        {
            name = "Zderzak przedni",
            type = "front bumper",
            icon = "files/images/frontBumper.png",
            offset = Vector3(0, 2, 0),
        },
        {
            name = "Zderzak tylni",
            type = "rear bumper",
            icon = "files/images/backBumper.png",
            offset = Vector3(0, -2, 0),
        },
        {
            name = "Progi",
            type = "sideskirt",
            icon = "files/images/hood.png",
            offset = Vector3(-2, 0, 0),
        },
        {
            name = "Wydech",
            type = "exhaust",
            icon = "files/images/exhaust.png",
            offset = Vector3(0, -2, 0),
            component = "exhaust_ok",
        },
        {
            name = "Spojler",
            type = "spoiler",
            icon = "files/images/spoiler.png",
            offset = Vector3(2, -2, 0),
        },
        {
            name = "Felgi",
            type = "wheels",
            icon = "files/images/rims.png",
            offset = Vector3(2, 2, 0),
            component = "wheel_lf_dummy",
        },
        {
            name = "Opuść tunera",
            type = "exit",
            icon = "files/images/exit.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
        },
        {
            name = "Kolorowe żarówki",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            isCustom = true,
            avaliableAll = true,
        },
        {
            name = "Kolor licznika",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            isCustom = true,
            avaliableAll = true,
        },
        {
            name = "Przyciemnianie szyb",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            isCustom = true,
            avaliableAll = true,
            isPremium = true,
        },
        {
            name = "Poszerzanie opon",
            type = "wheelResize",
            icon = "files/images/tiresize.png",
            offset = Vector3(2, 4, 0),
            isCustom = true,
            avaliableAll = true,
            isPremium = true,
        },
        {
            name = "Negatyw",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            isCustom = true,
            avaliableAll = true,
            isPremium = true,
        },
        {
            name = "Neony",
            type = "neon",
            icon = "files/images/neon.png",
            offset = Vector3(2, 0, 0),
            avaliableAll = true,
            isCustom = true,
            isPremium = true,
        },
        {
            name = "Variant",
            type = "variant",
            icon = "files/images/variant.png",
            offset = Vector3(2, 3, 0),
            isPremium = true,
        },
    },

    ["performance"] = {
        {
            name = "Turbo",
            type = "turbo",
            icon = "files/images/turbo.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Wałek rozrządu",
            type = "distribution",
            icon = "files/images/distribution.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Tłoki",
            type = "piston",
            icon = "files/images/piston.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Wtryski paliwa",
            type = "injection",
            icon = "files/images/injection.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Intercooler",
            type = "intercooler",
            icon = "files/images/intercooler.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Sprzęgło",
            type = "clutch",
            icon = "files/images/clutch.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Opuść tunera",
            type = "exit",
            icon = "files/images/exit.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Tarcze hamulcowe",
            type = "breaking",
            icon = "files/images/break.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Klocki hamulcowe",
            type = "breakpad",
            icon = "files/images/breakpad.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Układ kierowniczy",
            type = "steering",
            icon = "files/images/steering.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Zawieszenie",
            type = "suspension",
            icon = "files/images/suspension.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Przełożenie napędu",
            type = "drivetype",
            icon = "files/images/drivetype.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
    },
}

customUpgrades = {
    ["lamps"] = {
        {
            name = "Standard",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            element = {255,255,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Red",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {255,0,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "International Orange",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {255,85,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Orange",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {255,170,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Yellow",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {255,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Spring Bud",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {170,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Bright Green",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {85,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Lime",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {0,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Malachite",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {0,255,85},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Spring Green",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {0,255,170},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Cyan",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {0,255,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Deep Sky Blue",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {0,170,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Navy Blue",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {0,85,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Blue",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {0,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Electric Indigo",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {85,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Electric Purple",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {170,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Fuchsia",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {255,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Hollywood Cerise",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {255,0,170},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Razzmatazz",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {255,0,85},
            avaliableAll = true,
            isCustom = true,
        },
    },

    ["speedoColor"] = {
        {
            name = "Standard",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            element = {255,255,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Red",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 5200,
            element = {255,0,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "International Orange",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {255,85,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Orange",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {255,170,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Yellow",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {255,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Spring Bud",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {170,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Bright Green",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {85,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Lime",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {0,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Malachite",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {0,255,85},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Spring Green",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {0,255,170},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Cyan",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {0,255,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Deep Sky Blue",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {0,170,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Navy Blue",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {0,85,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Blue",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {0,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Electric Indigo",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {85,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Electric Purple",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {170,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Fuchsia",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {255,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Hollywood Cerise",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {255,0,170},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Razzmatazz",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {255,0,85},
            avaliableAll = true,
            isCustom = true,
        },
    },

    ["wheelResize"] = {
        {
            name = "Brak",
            type = "wheelResize",
            icon = "files/images/tiresize.png",
            offset = Vector3(2, 4, 0),
            element = 1,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+1",
            type = "wheelResize",
            icon = "files/images/tiresize.png",
            offset = Vector3(2, 4, 0),
            price = 4200,
            element = 1.1,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+2",
            type = "wheelResize",
            icon = "files/images/tiresize.png",
            offset = Vector3(2, 4, 0),
            price = 5000,
            element = 1.2,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+3",
            type = "wheelResize",
            icon = "files/images/tiresize.png",
            offset = Vector3(2, 4, 0),
            price = 6700,
            element = 1.3,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+4",
            type = "wheelResize",
            icon = "files/images/tiresize.png",
            offset = Vector3(2, 4, 0),
            price = 7800,
            element = 1.4,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+5",
            type = "wheelResize",
            icon = "files/images/tiresize.png",
            offset = Vector3(2, 4, 0),
            price = 9000,
            element = 1.5,
            avaliableAll = true,
            isCustom = true,
        },
    },

    ["wheelTilt"] = {
        {
            name = "Brak",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            element = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+1",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 4900,
            element = -1,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+2",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 5900,
            element = -2,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+3",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 7200,
            element = -3,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+4",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 8400,
            element = -4,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+5",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 9700,
            element = -5,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+6",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 10250,
            element = -6,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+7",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 11400,
            element = -7,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+8",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 12500,
            element = -8,
            avaliableAll = true,
            isCustom = true,
        },
    },

    ["glassTint"] = {
        {
            name = "Brak",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            element = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "95%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 4200,
            element = 0.05,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "90%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 5700,
            element = 0.1,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "80%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 7200,
            element = 0.2,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "70%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 8200,
            element = 0.3,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "60%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 9100,
            element = 0.4,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "50%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 10000,
            element = 0.5,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "40%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 11200,
            element = 0.6,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "30%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 12400,
            element = 0.7,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "20%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 13500,
            element = 0.8,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "10%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 14000,
            element = 0.9,
            avaliableAll = true,
            isCustom = true,
        },
    },

    ["turbo"] = {
        {
            name = "Brak",
            type = "turbo",
            icon = "files/images/turbo.png",
            offset = Vector3(0, 2, 0),
            element = false,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "1 Turbina",
            type = "turbo",
            icon = "files/images/turbo.png",
            offset = Vector3(0, 2, 0),
            element = "Turbo",
            value = 0.5,
            avaliableAll = true,
            isCustom = true,
            price = 18000,
        },
        {
            name = "2 Turbiny",
            type = "turbo",
            icon = "files/images/turbo.png",
            element = "Biturbo",
            offset = Vector3(0, 2, 0),
            value = 1,
            avaliableAll = true,
            isCustom = true,
            price = 25000,
        },
    },

    ["distribution"] = {
        {
            name = "Zwykły",
            type = "distribution",
            icon = "files/images/distribution.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Wzmocniony",
            type = "distribution",
            icon = "files/images/distribution.png",
            offset = Vector3(0, 2, 0),
            value = 0.2,
            avaliableAll = true,
            isCustom = true,
            price = 8400,
        },
        {
            name = "Zaostrzony",
            type = "distribution",
            icon = "files/images/distribution.png",
            offset = Vector3(0, 2, 0),
            value = 0.4,
            avaliableAll = true,
            isCustom = true,
            price = 9700,
        },
    },

    ["piston"] = {
        {
            name = "Aluminiowy",
            type = "piston",
            icon = "files/images/piston.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Stalowy",
            type = "piston",
            icon = "files/images/piston.png",
            offset = Vector3(0, 2, 0),
            value = 0.2,
            avaliableAll = true,
            isCustom = true,
            price = 8400,
        },
        {
            name = "Żeliwny",
            type = "piston",
            icon = "files/images/piston.png",
            offset = Vector3(0, 2, 0),
            value = 0.4,
            avaliableAll = true,
            isCustom = true,
            price = 9300,
        },
        {
            name = "Pozłacany",
            type = "piston",
            icon = "files/images/piston.png",
            offset = Vector3(0, 2, 0),
            value = 0.6,
            avaliableAll = true,
            isCustom = true,
            price = 13000,
        },
    },

    ["injection"] = {
        {
            name = "Standard",
            type = "injection",
            icon = "files/images/injection.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+10 mm",
            type = "injection",
            icon = "files/images/injection.png",
            offset = Vector3(0, 2, 0),
            value = 0.2,
            avaliableAll = true,
            isCustom = true,
            price = 8500,
        },
        {
            name = "+20 mm",
            type = "injection",
            icon = "files/images/injection.png",
            offset = Vector3(0, 2, 0),
            value = 0.4,
            avaliableAll = true,
            isCustom = true,
            price = 9500,
        },
        {
            name = "+30 mm",
            type = "injection",
            icon = "files/images/injection.png",
            offset = Vector3(0, 2, 0),
            value = 0.6,
            avaliableAll = true,
            isCustom = true,
            price = 12200,
        },
        {
            name = "+40 mm",
            type = "injection",
            icon = "files/images/injection.png",
            offset = Vector3(0, 2, 0),
            value = 0.8,
            avaliableAll = true,
            isCustom = true,
            price = 15800,
        },
    },

    ["intercooler"] = {
        {
            name = "Mały",
            type = "intercooler",
            icon = "files/images/intercooler.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Średni",
            type = "intercooler",
            icon = "files/images/intercooler.png",
            offset = Vector3(0, 2, 0),
            value = 0.1,
            avaliableAll = true,
            isCustom = true,
            price = 7400,
        },
        {
            name = "Duży",
            type = "intercooler",
            icon = "files/images/intercooler.png",
            offset = Vector3(0, 2, 0),
            value = 0.2,
            avaliableAll = true,
            isCustom = true,
            price = 8900,
        },
    },

    ["clutch"] = {
        {
            name = "Standard",
            type = "clutch",
            icon = "files/images/clutch.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Komfortowe",
            type = "clutch",
            icon = "files/images/clutch.png",
            offset = Vector3(0, 2, 0),
            value = -0.2,
            avaliableAll = true,
            isCustom = true,
            price = 5400,
        },
        {
            name = "Sportowe",
            type = "clutch",
            icon = "files/images/clutch.png",
            offset = Vector3(0, 2, 0),
            value = 0.1,
            avaliableAll = true,
            isCustom = true,
            price = 6400,
        },
        {
            name = "Torowe",
            type = "clutch",
            icon = "files/images/clutch.png",
            offset = Vector3(0, 2, 0),
            value = 0.2,
            avaliableAll = true,
            isCustom = true,
            price = 7800,
        },
    },

    ["breaking"] = {
        {
            name = "Standard",
            type = "breaking",
            icon = "files/images/break.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Komfortowe",
            type = "breaking",
            icon = "files/images/break.png",
            offset = Vector3(0, 2, 0),
            value = -0.5,
            avaliableAll = true,
            isCustom = true,
            price = 4200,
        },
        {
            name = "Sportowe",
            type = "breaking",
            icon = "files/images/break.png",
            offset = Vector3(0, 2, 0),
            value = 0.5,
            avaliableAll = true,
            isCustom = true,
            price = 5700,
        },
        {
            name = "Torowe",
            type = "breaking",
            icon = "files/images/break.png",
            offset = Vector3(0, 2, 0),
            value = 1,
            avaliableAll = true,
            isCustom = true,
            price = 7100,
        },
    },

    ["breakpad"] = {
        {
            name = "Standard",
            type = "breakpad",
            icon = "files/images/breakpad.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Komfortowe",
            type = "breakpad",
            icon = "files/images/breakpad.png",
            offset = Vector3(0, 2, 0),
            value = -0.5,
            avaliableAll = true,
            isCustom = true,
            price = 4200,
        },
        {
            name = "Sportowe",
            type = "breakpad",
            icon = "files/images/breakpad.png",
            offset = Vector3(0, 2, 0),
            value = 0.5,
            avaliableAll = true,
            isCustom = true,
            price = 5300,
        },
        {
            name = "Torowe",
            type = "breakpad",
            icon = "files/images/breakpad.png",
            offset = Vector3(0, 2, 0),
            value = 1,
            avaliableAll = true,
            isCustom = true,
            price = 6400,
        },
    },

    ["steering"] = {
        {
            name = "Standard",
            type = "steering",
            icon = "files/images/steering.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+5",
            type = "steering",
            icon = "files/images/steering.png",
            offset = Vector3(0, 2, 0),
            value = 5,
            avaliableAll = true,
            isCustom = true,
            price = 8500,
        },
        {
            name = "+10",
            type = "steering",
            icon = "files/images/steering.png",
            offset = Vector3(0, 2, 0),
            value = 10,
            avaliableAll = true,
            isCustom = true,
            price = 9400,
        },
        {
            name = "+15",
            type = "steering",
            icon = "files/images/steering.png",
            offset = Vector3(0, 2, 0),
            value = 15,
            avaliableAll = true,
            isCustom = true,
            price = 11000,
        },
        {
            name = "+20",
            type = "steering",
            icon = "files/images/steering.png",
            offset = Vector3(0, 2, 0),
            value = 20,
            avaliableAll = true,
            isCustom = true,
            price = 13400,
        },
    },

    ["suspension"] = {
        {
            name = "Standard",
            type = "suspension",
            icon = "files/images/suspension.png",
            offset = Vector3(0, 2, 0),
            value = false,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Hydraulika",
            type = "suspension",
            icon = "files/images/suspension.png",
            offset = Vector3(0, 2, 0),
            value = 1087,
            avaliableAll = true,
            isCustom = true,
            price = 20400,
        },
        {
            name = "Pneumatyka",
            type = "suspension",
            icon = "files/images/suspension.png",
            offset = Vector3(0, 2, 0),
            value = true,
            avaliableAll = true,
            isCustom = true,
            price = 16000,
        },
    },

    ["drivetype"] = {
        {
            name = "Napęd na przód",
            type = "drivetype",
            icon = "files/images/drivetype.png",
            offset = Vector3(0, 2, 0),
            value = "fwd",
            avaliableAll = true,
            isCustom = true,
            price = 9500,
        },
        {
            name = "Napęd na tył",
            type = "drivetype",
            icon = "files/images/drivetype.png",
            offset = Vector3(0, 2, 0),
            value = "rwd",
            avaliableAll = true,
            isCustom = true,
            price = 10000,
        },
        {
            name = "Napęd 4x4",
            type = "drivetype",
            icon = "files/images/drivetype.png",
            offset = Vector3(0, 2, 0),
            value = "awd",
            avaliableAll = true,
            isCustom = true,
            price = 12500,
        },
    },
}


function getCustomUpgrades()
    return customUpgrades
end

neonColors = {
    {255, 0, 0, "Red"},
    {255, 85, 0, "International Orange"},
    {255, 170, 0, "Orange"},
    {255, 255, 0, "Yellow"},
    {170, 255, 0, "Spring Bud"},
    {85, 255, 0, "Bright Green"},
    {0, 255, 0, "Lime"},
    {0, 255, 85, "Malachite"},
    {0, 255, 170, "Spring Green"},
    {0, 255, 255, "Cyan"},
    {0, 170, 255, "Deep Sky Blue"},
    {0, 85, 255, "Navy Blue"},
    {0, 0, 255, "Blue"},
    {85, 0, 255, "Electric Indigo"},
    {170, 0, 255, "Electric Purple"},
    {255, 0, 255, "Fuchsia"},
    {255, 0, 170, "Hollywood Cerise"},
    {255, 0, 85, "Razzmatazz"},
}

performanceValuesMax = {
    ["engineAcceleration"] = 50,
    ["maxVelocity"] = 450,
    ["tractionMultiplier"] = 1.6,
    ["brakeDeceleration"] = 35,
    ["steeringLock"] = 60,
    ["fuelTake"] = 50,
}

upgradeNames = {
    "Pro", "Win", "Drag", "Alpha", "Champ Scoop", "Fury Scoop", "Scoop", "Próg", "Nitro x5",
    "Nitro x2", "Nitro x10", "Race Scoop", "Worx Scoop", "okrągłe Fog", "Champ", "Race", "Worx", "Próg",
    "Upswept", "Twin", "duży", "średni", "mały", "Fury", "kwadratowe Fog", "Offroad", "Alien",
    "Alien", "Alien", "X-Flow", "X-Flow", "X-Flow", "Alien Vent", "X-Flow Vent", "Alien", "X-Flow Vent",
    "Alien", "WydeExhaustch X-Flow", "Alien Vent", "X-Flow", "Alien", "X-Flow", "Alien", "Slamin", "Chrome",
    "X-Flow", "Alien", "Alien", "X-Flow", "Alien", "X-Flow", "Alien", "X-Flow", "X-Flow", "Alien",
    "Alien", "Alien", "X-Flow", "Alien", "X-Flow", "X-Flow", "X-Flow", "Alien", "X-Flow", "Alien",
    "Alien", "X-Flow", "Alien", "X-Flow", "Alien", "X-Flow", "Alien", "X-Flow", "Shadow", "Mega",
    "Rimshine", "Wires", "Classic", "Twist", "Cutter", "Switch", "Grove", "Import", "Dollar", "Trance", "Atomic",
    "Stereo", "Hydraulika", "Alien", "X-Flow", "Alien", "X-Flow", "Alien", "X-Flow", "Alien", "X-Flow",
    "Ahab", "Virtual", "Access", "Chrome", "Osłona zderzaka Chrome Grill", "Chrome Flames", "Chrome Strip", "Covertible",
    "Chrome", "Slamin", "Chrome Arches", "Chrome Strip", "Chrome Strip", "Chrome", "Slamin",
    "Front Little Sign", "Front Little Sign 2", "Chrome", "Slamin", "Przednie osłony Chrome", "Przednie osłony Slamin", "Chrome",
    "Chrome Trim", "Wheelcovers", "Chrome Trim", "Wheelcovers", "Chrome Flames", "Osłony Chrome Bars",
    "Chrome Arches", "Osłony Chrome Lights", "Chrome", "Slamin", "Vinyl Hardtop", "Chrome", "Hardtop", "Softtop",
    "Slamin", "Chrome Strip", "Chrome Strip", "Slamin", "Chrome", "Chrome Strip", "Alien", "X-Flow",
    "X-Flow", "Alien", "Okrągła wentylacja", "Okrągła wentylacja", "kwadratowa wentylacja", "kwadratowa wentylacja",
    "X-Flow", "Alien", "X-Flow", "Alien", "Alien", "X-Flow", "X-Flow",
    "Alien", "Alien", "Alien", "X-Flow", "X-Flow", "X-Flow", "Alien",
    "Alien", "X-Flow", "Alien", "X-Flow", "Alien", "X-Flow", "Alien", "X-Flow",
    "Alien", "Alien", "X-Flow", "Alien", "X-Flow", "X-Flow", "Chrome",
    "Slamin", "Chrome", "Slamin", "Slamin", "Chrome", "Chrome", "Slamin",
    "Chrome", "Slamin", "Chrome", "Slamin", "Slamin", "Chrome", "Slamin",
    "Chrome", "Slamin", "Chrome", "Slamin", "Chrome"
}

prices = {
    [1025]=3200,
    [1073]=5100,
    [1074]=4600,
    [1075]=4600,
    [1076]=4400,
    [1077]=4700,
    [1078]=4900,
    [1079]=4400,
    [1080]=4800,
    [1081]=5200,
    [1082]=4900,
    [1083]=5500,
    [1084]=5300,
    [1085]=4600,
    [1097]=4800,


--  Stereo
	[1086]=3000,
--  Spoilery
	[1000]=2000,
	[1001]=2500,
	[1002]=2000,
	[1003]=2500,
	[1014]=1400,
	[1015]=2000,
	[1016]=2100,
	[1023]=2400,
	[1049]=1540,
	[1050]=1300,
	[1058]=1300,
	[1060]=1750,
	[1138]=3900,
	[1139]=3400,
	[1146]=3000,
	[1147]=3500,
	[1158]=4100,
	[1162]=2900,
	[1163]=2000,
	[1164]=4500,
--	Progi
	[1036]=1500,
	[1039]=2000,
	[1040]=1870,
	[1041]=2300,
	[1007]=1000,
	[1017]=1000,
	[1026]=1500,
	[1027]=2000,
	[1030]=1500,
	[1031]=2300,
	[1042]=1000,
	[1047]=1890,
	[1048]=1730,
	[1051]=2000,
	[1052]=1800,
	[1056]=1000,
	[1057]=1000,
	[1062]=1000,
	[1063]=1250,
	[1069]=1800,
	[1070]=1500,
	[1071]=1650,
	[1072]=1750,
	[1090]=1750,
	[1093]=1700,
	[1094]=1500,
	[1095]=1000,
	[1099]=1000,
	[1101]=1000,
	[1102]=7000,
	[1106]=1000,
	[1107]=1000,
	[1108]=1000,
	[1118]=7000,
	[1119]=7000,
	[1120]=7000,
	[1121]=7000,
	[1122]=7000,
	[1124]=7000,
	[1133]=1000,
	[1134]=1000,
	[1137]=1000,

--  Bullbar . . ? [przod]
	[1100]=7500,
	[1115]=7500,
	[1116]=7500,
	[1123]=7500,
	[1125]=10000,
--  Bullbar . . ? [tył]
	[1109]=9000,
	[1110]=3000,
--	Front Sign [figurka itd z przodu]
	[1111]=6500,
	[1112]=6500,
--	Hydraulika
	[1087]=35100,
--  Wydechy
	[1034]=1900,
	[1037]=2000,
	[1044]=1800,
	[1046]=2000,
	[1018]=1700,
	[1019]=1900,
	[1020]=2000,
	[1021]=1800,
	[1022]=1800,
	[1028]=1900,
	[1029]=2000,
	[1043]=1500,
	[1044]=1000,
	[1045]=1500,
	[1059]=1500,
	[1064]=1200,
	[1065]=1300,
	[1066]=1500,
	[1089]=2000,
	[1092]=1750,
	[1104]=1650,
	[1105]=1400,
	[1113]=1200,
	[1114]=1750,
	[1126]=1000,
	[1127]=1100,
	[1129]=1000,
	[1132]=1500,
	[1135]=1000,
	[1136]=1500,

--  Zderzaki [tylni]
	[1149]=4000,
	[1148]=5000,
	[1150]=3000,
	[1151]=3500,
	[1154]=3000,
	[1156]=3000,
	[1159]=3500,
	[1161]=3600,
	[1167]=3000,
	[1168]=2500,
	[1175]=2500,
	[1177]=2500,
	[1178]=2900,
	[1180]=3100,
	[1183]=2700,
	[1184]=3000,
	[1186]=3000,
	[1187]=2600,
	[1192]=2000,
	[1193]=2000,
--  Zderzaki [pzrzód]
	[1171]=3500,
	[1172]=5000,
	[1140]=3500,
	[1141]=5000,
	[1117]=5000,
	[1152]=3000,
	[1153]=3500,
	[1155]=3000,
	[1153]=3000,
	[1157]=3000,
	[1160]=4000,
	[1165]=4000,
	[1166]=3000,
	[1169]=3000,
	[1170]=3500,
	[1173]=3500,
	[1174]=2500,
	[1176]=2500,
	[1179]=3500,
	[1181]=2500,
	[1182]=2300,
	[1185]=3000,
	[1188]=3200,
	[1189]=2900,
	[1190]=2500,
	[1191]=2100,
--  Wloty [góra]
	[1035]=3000,
	[1038]=3500,
	[1006]=1960,
	[1032]=3000,
	[1033]=3500,
	[1053]=3500,
	[1054]=3000,
	[1055]=2000,
	[1061]=2000,
	[1068]=3250,
	[1067]=2750,
	[1088]=2300,
	[1091]=3000,
	[1103]=1500,
	[1128]=5000, -- DACH DO BLADE
	[1130]=5000, -- DACH DO SAVANNA
	[1131]=5000, -- DACH DO SAVANNA
--  Wloty [przód]
	[1004]=1400,
	[1005]=1600,
	[1011]=1400,
	[1012]=1600,
	[1142]=1200,
	[1143]=1200,
	[1144]=1000,
	[1145]=1000,
--	Dodatkowe lampy
	[1013]=7000,
	[1024]=8000,
}
